filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/readonly/*.log
  encoding: utf-8
output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/share/filebeat/logs
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
