input {
  tcp {
    port => 5044
    codec => json
  }
  udp {
    port => 5044
    codec => json
  }
}

filter {
  if [event_type] == "alert" {
    mutate {
      add_field => { "[@metadata][index]" => "suricata-alerts-%{+YYYY.MM.dd}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index]" => "suricata-events-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index]}"
  }
}
