version: '3.8'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.4
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/suricata:/var/log/suricata:ro
    networks:
      - suricata_elk
    restart: unless-stopped

networks:
  suricata_elk:
    external: true
    name: elk_elk
