input {
  beats {
    port => 5044
  }
}

filter {
  if [path] =~ "eve.json" {
    json {
      source => "message"
      target => "suricata"
    }
    mutate {
      add_field => { "event.module" => "suricata" }
    }

    geoip {
      source => "dest_ip"
      target => "destination.geoip"
    }
  }
}

output {
  if [path] =~ "eve.json" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "suricata-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logstash-%{+YYYY.MM.dd}"
    }
  }
}
